### ISSUE TITLE
Update README for release

### ISSUE THREAD

**Issue by egouldo** [metamelb-repliCATS/aggreCAT#1]
From @doi90:
- [x] intro / description paragraph
- [x] overview core concept of egg method
- [x] how to install
- [x] ARMean fig
- [x] @psychtek 's fancy badges
- [x] license info
- [x] How many methods do we have in total?

**Comment by psychtek** [comment]
@egouldo the testing badges should self update once I setup the Github Actions! 🥳

**Comment by egouldo** [comment]
Excellent, I thought so!

**Comment by egouldo** [comment]
@psychtek do you know how many methods are available in the package in total, just updating now.

**Comment by psychtek** [comment]
39 overall that we have run

**Comment by egouldo** [comment]
- [ ] group count on `methods` in `data_confidence_scores`
