### ISSUE TITLE
Pkgdown blog site

### ISSUE THREAD

**Issue by psychtek** [metamelb-repliCATS/aggreCAT#13]
Do we want to have a [pkgdown](https://pkgdown.r-lib.org/index.html) blog site? 

> pkgdown will automatically build all vignettes found in vignettes/, translating them to HTML files in articles
> pkgdown creates a function reference in reference/ that includes one page for each .Rd help topic in man/

**Comment by Doi90** [comment]
I think it's definitely worth adding

**Comment by egouldo** [comment]
Closing because https://github.com/metamelb-repliCATS/aggreCAT/commit/bb3e4f801721089bb8dd9f6ec528ba49153b9915 fixes this
