### ISSUE TITLE
cli:: output PITA ugly in LaTeX generated PDf

### ISSUE THREAD

**Issue by egouldo** [metamelb-repliCATS/aggreCAT#19]
For instance:
![image](https://user-images.githubusercontent.com/8400682/195225418-7ff55ce4-b72d-4344-9e94-241200cfc420.png)

How do we stop this from taking up the whole goddamn page?
Should we just set chunk options `message: false` ?? or can we pretty it up with `cli::` somehow??

**Comment by egouldo** [comment]
I've set quarto chunk options to `message: false`, and this just removes all console outputs. I think this is a good enough option for now.

Let's focus on other issues, and perhaps we will close (not planned).

**Comment by psychtek** [comment]
I tinkered with options but like youve already done - the output can be suppressed either through `options()` at the console of script level.
