### ISSUE TITLE
Appendices?

### ISSUE THREAD

**Issue by egouldo** [metamelb-repliCATS/aggreCAT#21]
What appendices do we need?

If so, can be generated using the quarto JSS template like so:

> Appendices can be included after the bibliography (with a page break). Each section within the appendix should have a proper section title (rather than just Appendix).

**Comment by Doi90** [comment]
I'm not sure that we need any appendices for this paper? Unless you wanted to include a full workflow script example or something, but even that I think is best left as just an extra package vignette IMO.

**Comment by egouldo** [comment]
Agreed. I've used 'code listings' to move code to the back of the paper so it doesn't clog up the main manuscript, and I think that's better than having separate appendices for now. Anything else can go in the vignettes as you suggest.
