### ISSUE TITLE
separate ' code display' chunks from 'code used for creating manuscript outputs'

### ISSUE THREAD

**Issue by egouldo** [metamelb-repliCATS/aggreCAT#24]
![image](https://user-images.githubusercontent.com/8400682/195270517-eb9f5225-d222-4e9a-bbf6-bf379c8c306a.png)

e.g. in the photo above, we don't want to expose the code showing table creation with `gt::`, we just want to show the code that generates the confidence scores. 
In the current example the CS generation is saved to object `turtle_CS`.. but we don't want this displayed in the manuscript.

This issue applies to other code chunks generating gt / latex tables and/or visualisations

**Comment by Doi90** [comment]
Can't you just set `echo=FALSE` in the code chunks where applicable?

**Comment by egouldo** [comment]
Checked all tables/figs and this has been resolved in #30, with relevant code we want to expose to users shifted into listings or echo'd chunks.
