### ISSUE TITLE
Update percent_toggle text in blue print box

### ISSUE THREAD

**Issue by egouldo** [metamelb-repliCATS/aggreCAT#26]
Current text is incorrect I think. I have clarified this with @Doi90 and @psychtek in today's meeting.

**Explain:**
- [x] when `percent_toggle` is set to `TRUE`, judgement values are _converted_ into probabilities , i.e. divided by 100. When set to `FALSE` this behaviour doesn't occur. 

**Code:**
- [x] sea turtle / BYO data code should be set to `FALSE`
- [x] probabilities for `BayesianWAgg()` should be set to `TRUE`

**Check error handling behaviour in fn:**
- [x] values outside of $[0,1]$ should give warning.

**Comment by psychtek** [comment]
You have discovered one of the ones I forgot to switch to default - Bays! Public release we are of the view that `FALSE` will be the default setting to allow for other data types. But we had these `TRUE` (percentage) for our aggregation formats. So for print we had these **on** or `TRUE` given our direct replication questions were probabilities.

**Comment by psychtek** [comment]
I have added a warning to the code that I am creating tests for so should be added shortly.

**Comment by egouldo** [comment]
I'm closing this issue because all tasks have been addressed within PR #30
