### ISSUE TITLE
Auto count the number of methods in manuscript, following README

### ISSUE THREAD

**Issue by egouldo** [metamelb-repliCATS/aggreCAT#28]
- [x] group count on `methods` in `data_confidence_scores`

Great. I'll put the code inline in the README, so once you've removed methods with demo/user data, it should update automatically.

_Originally posted by @egouldo in https://github.com/metamelb-repliCATS/aggreCAT/issues/1#issuecomment-1235000787_

**Comment by Doi90** [comment]
This wont match numbers. The `data_confidence_scores` object will have a lot of agg method names that are just using the user-supplied weights option.

**Comment by egouldo** [comment]
Yep, closing now. We've got the numbers for the manuscript now anyway (27 + 2 user for reference).
