### ISSUE TITLE
Ridgeline plots: pare down aesthetics, investigate weighted linear combos

### ISSUE THREAD

**Issue by egouldo** [metamelb-repliCATS/aggreCAT#33]
> Ok, so this is my first time seeing the output of this function and it isn't what I expected. I thought this was supposed to match what @psychtek had done previously where they were grey-ish and had red/blue top/bottom 5% quantiles? The old-school WordArt colour scheme has to go. I get the dashed line is the 0.5 line, but what is the solid line? Distribution mean? Why is it the same for all distirbutions in Weighted Linear Combinations? In terms of overall aesthetics I think we should go back to just standard `theme_bw()` to keep boxes/gridlines (willing to lose gridlines though), and not get rid of the facet label boxes. We should keep things relatively simple and let users "expand" on it with their own ggplot modifications. I would be _very negative_ about this figure if I was reviewing it in a manuscript as it has made aesthetic choices that make the "science" harder to interpret (regardless of my opinions of aesthetics)

_Originally posted by @Doi90 in https://github.com/metamelb-repliCATS/aggreCAT/pull/30#discussion_r1021458146_

**Comment by psychtek** [comment]
Ok sorry been buried in new work stuff. I'll look back through but I remember when we were tinkering with the plots like a year ago so should be able to roll back the change easily. 
Have a little time this week to check this out.

**Comment by psychtek** [comment]
Ive updated/ported the plot into the msedits branch - I had to dig into my memory banks and recall what was where! I think that blue one was something we were tinkering with and than got ported. Either way the updated one is on master but I dont think was branched into the `meedits` branch. 

This one is split by type and aesthetics and stuff removed. Let me know what additional tweaks you need 
 
![Rplot](https://user-images.githubusercontent.com/40842621/227823323-5f4cdfb5-5b6d-4b42-aba7-635b036ac98c.png)

**Comment by Doi90** [comment]
Thanks @psychtek! I can take it from here, I think I might remove the facetting for now so that there isn't issues with non-comparable y-axis scales.

**Comment by Doi90** [comment]
Fixed in #49
