### ISSUE TITLE
Update blocked heat map function faceting and aesthetics

### ISSUE THREAD

**Issue by egouldo** [metamelb-repliCATS/aggreCAT#34]
> This figure is _waaaaayyy_ better than the previous one. But I have a few suggestions still:
> - I don't think the supp data methods should be their own facet. They're different from a code implementation perspective, but not statistically, and when you're visualising the results you're not considering code implementation anymore.
> - As per previous plot, go back to base `theme_bw()` and keep facet label boxes, also drop italics inf facet labels. And is the legend title in a different font?

_Originally posted by @Doi90 in https://github.com/metamelb-repliCATS/aggreCAT/pull/30#discussion_r1021463087_

**Comment by Doi90** [comment]
Fixed in #49
