### ISSUE TITLE
Consider adding DescTools:: as dependency to pkg

### ISSUE THREAD

**Issue by egouldo** [metamelb-repliCATS/aggreCAT#36]
`aggreCAT::confidence_score_evaluation()` requires DescTools::BriefScore() for Brier score calculation. Should we not stipulate this as an explicit dependency?

**Comment by Doi90** [comment]
Yes we should. Surprised it never got flagged in any of the build tests tbh.

**Comment by egouldo** [comment]
For this function, also add the following importFrom:

- precrec::evalmod
- precrec::auc
- rfUtilities::accuracy
