### ISSUE TITLE
Remove methods with demo/user data

### ISSUE THREAD

**Issue by egouldo** [metamelb-repliCATS/aggreCAT#4]
See:

39 overall that we have run. But without demographic and user stuff it'll be a couple less 🤔 
Do a group count on the `methods` in the `data_confidence_scores` to confirm. 
Tests will be different once I've removed the ones referencing the demo and user data.

_Originally posted by @psychtek in https://github.com/metamelb-repliCATS/aggreCAT/issues/1#issuecomment-1234972726_

**Comment by psychtek** [comment]
Do we want the count of methods run as per release of package or in the manuscript? As user and demographics wasnt included (BadgeWAgg for example) then the agg methods count will differ.

**Comment by egouldo** [comment]
Yeah I think it’s a good idea, that way we can keep it current without having to remember to update every time!

Sent from my iPhone

On 7 Sep 2022, at 12:15 pm, Aaron ***@***.***> wrote:

﻿

Do we want the count of methods run as per release of package or in the manuscript? As user and demographics wasnt included (BadgeWAgg for example) then the agg methods count will differ.
